-- Automatically generated by Makefile.  Do not change.
module Ideas.Main.Revision where

ideasVersion :: String
ideasVersion = "1.4"

ideasRevision :: Int
ideasRevision = 8775

ideasLastChanged :: String
ideasLastChanged = "vr, 23 okt 2015"
